### ISSUE TITLE
"Questions asked by suppliers" wraps awkwardly on Safari when it contains long links

### ISSUE THREAD

**Issue by tvararu** [alphagov/digitalmarketplace-buyer-frontend#1014]
See https://www.digitalmarketplace.service.gov.uk/digital-outcomes-and-specialists/opportunities/12107

This is how it looks:

![Screenshot 2020-04-14 at 13 33 28](https://user-images.githubusercontent.com/1650875/79225456-a0e5f880-7e54-11ea-8aa3-02e93a942d12.png)

I think adding `word-break: break-all;` to anchor tags inside summary tables could be enough to fix this:

![Screenshot 2020-04-14 at 13 35 59](https://user-images.githubusercontent.com/1650875/79225593-e276a380-7e54-11ea-8ca2-e5966ea35a10.png)

Let me know if you'd like a PR with that!

**Comment by katstevens** [comment]
Thanks for raising this issue @tvararu. We'll add it to our backlog.
