### ISSUE TITLE
No mention of the search app in the documentation

### ISSUE THREAD

**Issue by tombye** [alphagov/digitalmarketplace-buyer-frontend#8]
The buyer frontend app now relies on the search API for its search results but this is not mentioned in the README other than mentioning the need for DM_SEARCH_API environment variable.

**Comment by TheDoubleK** [comment]
It kind-of does mention it: "for dev use local API instances if you have them running" refers to the search API and data API.  But I'll make it clearer.

**Comment by TheDoubleK** [comment]
@tombye I think this should do it?  https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/10

**Comment by TheDoubleK** [comment]
I know the preview environment doesn't entirely exist yet, but it should do in the next day or so, so seems OK to put it in the README now.
