### ISSUE TITLE
No mention of DM_BUYER_FRONTEND_API_AUTH_TOKEN in the documentation

### ISSUE THREAD

**Issue by tombye** [alphagov/digitalmarketplace-buyer-frontend#9]
DM_BUYER_FRONTEND_API_AUTH_TOKEN needs to match the one set for the search API app but this is not mentioned in the README.

**Comment by tombye** [comment]
This is incorrect. It has been renamed from DM_API_BEARER which is mentioned in the README. Closing this issue.

**Comment by TheDoubleK** [comment]
I'm not sure what you mean?  The auth tokens can be different for the search API and for the data API.
So:
DM_BUYER_FRONTEND_API_AUTH_TOKEN needs to be a token accepted by the DATA API
DM_BUYER_FRONTEND_SEARCH_API_AUTH_TOKEN needs to be a token accepted by the Search API

**Comment by tombye** [comment]
I mentioned my misunderstanding but having something like your explanation in the README would be great.

**Comment by TheDoubleK** [comment]
Sorry, I hadn't seen your comment when I posted mine - think they went at the same time!
